[profile.default]
src = "contracts"
out = "out"
libs = ["../../node_modules", "lib", "node_modules"]
test = "test"
cache_path = "cache_forge"
allow_paths = ["../../node_modules", "../v3-core", "../router", "../masterchef-v3", "../v3-lm-pool", "forge-std", "../contracts", "lib"]

# Compiler settings
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200_000_000
bytecode_hash = "none"


# Contract-specific optimizer settings (matching Hardhat overrides)
[profile.low_optimizer]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2_000
bytecode_hash = "none"


[profile.mid_lowest_optimizer]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200_000
bytecode_hash = "none"


[profile.lowest_optimizer]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"

[profile.minimal_size]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

# Remappings
remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "@kasplex/v3-core/=../v3-core/",
    "@kasplex/v3-lm-pool/=../v3-lm-pool/",
    "@kasplex/masterchef-v3/=../masterchef-v3/",
    "@kasplex/router/=../router/",
]

# Network configurations
[rpc_endpoints]
kasplex_testnet = "https://rpc.kasplextest.xyz"
kasplex_mainnet = "https://rpc.kasplextest.xyz"  # Using testnet RPC for now as requested

[etherscan]
kasplex_testnet = { key = "MNNUYHJNPKZN5BIGCC4K8IH9PA9TB68G5J", chainId = 167012, url = "https://explorer.testnet.kasplextest.xyz/api" }
kasplex_mainnet = { key = "MNNUYHJNPKZN5BIGCC4K8IH9PA9TB68G5J", chainId = 167012, url = "https://explorer.testnet.kasplextest.xyz/api" }

# Forge configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]
