[profile.default]
src = "contracts"
out = "out"
libs = ["../../node_modules", "lib", "node_modules"]
test = "test"
script = "script"
cache_path = "cache_forge"
allow_paths = ["../../node_modules", "../v3-core", "../v3-periphery", "../masterchef-v3", "../v3-lm-pool"]

# Compiler settings (default 0.7.6 for this project)
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"


# Support for multiple Solidity versions used by router
[profile.v0_7_6]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"

[profile.v0_8_10]
solc_version = "0.8.10"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"

[profile.v0_6_6]
solc_version = "0.6.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"

[profile.v0_5_16]
solc_version = "0.5.16"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"

[profile.v0_4_18]
solc_version = "0.4.18"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 2000
bytecode_hash = "none"

[profile.minimal_size]
solc_version = "0.7.6"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

# Remappings
remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "forge-std/=lib/forge-std/src/",
    "@kasplex/v3-core/contracts/=../v3-core/contracts/",
    "@kasplex/v3-periphery/contracts/=../v3-periphery/contracts/",
    "@kasplex/masterchef-v3/contracts/=../masterchef-v3/contracts/",
    "@kasplex/v3-lm-pool/contracts/=../v3-lm-pool/contracts/",
    "@kasplex/v3-core/=../v3-core/",
    "@kasplex/v3-periphery/=../v3-periphery/",
    "@kasplex/masterchef-v3/=../masterchef-v3/",
    "@kasplex/v3-lm-pool/=../v3-lm-pool/",
    "@kasplex/=../../node_modules/@kasplex/",
]

# Network configurations
[rpc_endpoints]
kasplex_testnet = "https://rpc.kasplextest.xyz"
kasplex_mainnet = "https://rpc.kasplextest.xyz"  # Using testnet RPC for now as requested

[etherscan]
kasplex_testnet = { key = "MNNUYHJNPKZN5BIGCC4K8IH9PA9TB68G5J", chainId = 167012, url = "https://explorer.testnet.kasplextest.xyz/api" }
kasplex_mainnet = { key = "MNNUYHJNPKZN5BIGCC4K8IH9PA9TB68G5J", chainId = 167012, url = "https://explorer.testnet.kasplextest.xyz/api" }

# Forge configuration
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["test/**/*"]
